services:
  db:
    image: postgres:15-alpine
    container_name: energiflow_db
    restart: always
    environment:
      POSTGRES_DB: energiflowdb
      POSTGRES_USER: energiflow_user
      POSTGRES_PASSWORD: energiflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - energiflow_net

  backend:
    build:
      context: ./backend
    container_name: energiflow_backend
    restart: always
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/energiflowdb
      SPRING_DATASOURCE_USERNAME: energiflow_user
      SPRING_DATASOURCE_PASSWORD: energiflow_password
    depends_on:
      - db
    networks:
      - energiflow_net

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8088
    container_name: energiflow_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - energiflow_net

networks:
  energiflow_net:
    driver: bridge

volumes:
  postgres_data:
